customhost = "database-1.cd9ieuxxz6h0.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chengzhilin-employee"
customregion = "us-east-1"